In [ ]:
!wget -nc https://lazyprogrammer.me/course_files/nlp/bbc_text_cls.csv

--2023-09-05 18:52:59--  https://lazyprogrammer.me/course_files/nlp/bbc_text_cls.csv
Resolving lazyprogrammer.me (lazyprogrammer.me)... 104.21.23.210, 172.67.213.166, 2606:4700:3031::6815:17d2, ...
Connecting to lazyprogrammer.me (lazyprogrammer.me)|104.21.23.210|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5085081 (4.8M) [text/csv]
Saving to: ‘bbc_text_cls.csv’

bbc_text_cls.csv    100%[===================>]   4.85M  1.72MB/s    in 2.8s    

2023-09-05 18:53:04 (1.72 MB/s) - ‘bbc_text_cls.csv’ saved [5085081/5085081]



In [ ]:
import pandas as pd
import numpy as np
import nltk

from sklearn.feature_extraction.text import CountVectorizer
from nltk import word_tokenize

In [ ]:
nltk.download("punkt")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
df = pd.read_csv("bbc_text_cls.csv")

In [ ]:
df.head()

text    labels
0  Ad sales boost Time Warner profit\n\nQuarterly...  business
1  Dollar gains on Greenspan speech\n\nThe dollar...  business
2  Yukos unit buyer faces loan claim\n\nThe owner...  business
3  High fuel prices hit BA's profits\n\nBritish A...  business
4  Pernod takeover talk lifts Domecq\n\nShares in...  business

In [ ]:
idx = 0
word2idx = {}
tokenized_docs = []
for doc in df["text"]:
  words = word_tokenize(doc.lower())
  doc_as_int = []
  for word in words:
    if word not in word2idx:
      word2idx[word] = idx
      idx +=1

    doc_as_int.append(word2idx[word])
  tokenized_docs.append(doc_as_int)

In [ ]:
# reverse mapping
# if you do it smarter you can store it as a list
idx2word = {v:k for k, v in word2idx.items()}
idx2word

{0: 'ad',
 1: 'sales',
 2: 'boost',
 3: 'time',
 4: 'warner',
 5: 'profit',
 6: 'quarterly',
 7: 'profits',
 8: 'at',
 9: 'us',
 10: 'media',
 11: 'giant',
 12: 'timewarner',
 13: 'jumped',
 14: '76',
 15: '%',
 16: 'to',
 17: '$',
 18: '1.13bn',
 19: '(',
 20: '£600m',
 21: ')',
 22: 'for',
 23: 'the',
 24: 'three',
 25: 'months',
 26: 'december',
 27: ',',
 28: 'from',
 29: '639m',
 30: 'year-earlier',
 31: '.',
 32: 'firm',
 33: 'which',
 34: 'is',
 35: 'now',
 36: 'one',
 37: 'of',
 38: 'biggest',
 39: 'investors',
 40: 'in',
 41: 'google',
 42: 'benefited',
 43: 'high-speed',
 44: 'internet',
 45: 'connections',
 46: 'and',
 47: 'higher',
 48: 'advert',
 49: 'said',
 50: 'fourth',
 51: 'quarter',
 52: 'rose',
 53: '2',
 54: '11.1bn',
 55: '10.9bn',
 56: 'its',
 57: 'were',
 58: 'buoyed',
 59: 'by',
 60: 'one-off',
 61: 'gains',
 62: 'offset',
 63: 'a',
 64: 'dip',
 65: 'bros',
 66: 'less',
 67: 'users',
 68: 'aol',
 69: 'on',
 70: 'friday',
 71: 'that',
 72: 'it',
 73: 'owns',
 74

In [ ]:
N = len(df["text"])

In [ ]:
vectorizer = CountVectorizer()

In [ ]:
vectorizer.fit(df["text"])
print("Vocabulary: ", vectorizer.vocabulary_)

Vocabulary:  {'ad': 1750, 'sales': 23062, 'boost': 4349, 'time': 26665, 'warner': 28502, 'profit': 20825, 'quarterly': 21204, 'profits': 20832, 'at': 2994, 'us': 27901, 'media': 17064, 'giant': 11826, 'timewarner': 26677, 'jumped': 14933, '76': 1249, 'to': 26730, '13bn': 184, '600m': 1105, 'for': 11102, 'the': 26462, 'three': 26566, 'months': 17692, 'december': 7736, 'from': 11377, '639m': 1136, 'year': 29256, 'earlier': 9183, 'firm': 10842, 'which': 28749, 'is': 14510, 'now': 18557, 'one': 18837, 'of': 18726, 'biggest': 3963, 'investors': 14406, 'in': 13801, 'google': 12066, 'benefited': 3816, 'high': 13002, 'speed': 24836, 'internet': 14299, 'connections': 6653, 'and': 2429, 'higher': 13005, 'advert': 1885, 'said': 23041, 'fourth': 11224, 'quarter': 21203, 'rose': 22793, '11': 106, '1bn': 461, '10': 68, '9bn': 1466, 'its': 14571, 'were': 28694, 'buoyed': 4868, 'by': 4980, 'off': 18730, 'gains': 11534, 'offset': 18758, 'dip': 8384, 'bros': 4713, 'less': 15809, 'users': 27919, 'aol': 2

In [ ]:
vector = vectorizer.transform(df["text"])
print("Encoded Document is:")
print(vector.toarray())

Encoded Document is:
[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


In [ ]:
np.random.seed(12)

In [ ]:
i = np.random.choice(vector.shape[0])
row = df.iloc[i]
print("Label: ", row["labels"])
print("Text: ", row["text"].split("\n", 1)[0])
print("Top 5 terms:")

scores = vector[i]
indices = np.argsort(-vector.toarray())[0]
print(f"{indices}")
for j in indices[:5]:
    print(vectorizer.get_feature_names_out()[j])

0
Label:  business
Text:  Ad sales boost Time Warner profit
Top 5 terms:
[26462 18726 11102 ...  9819  9817 29420]
the
of
for
to
information
