In [2]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [5]:
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units
# K = number of output units

In [7]:
# Make some data
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [9]:
# Make an RNN
M = 5 # number of hidden units
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

In [10]:
# Get the output
Yhat = model.predict(X)
print(Yhat)

1/1 [==============================] - 0s 355ms/step
[[ 1.2073078 -1.0379326]]


In [11]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn (SimpleRNN)      (None, 5)                 45        
                                                                 
 dense (Dense)               (None, 2)                 12        
                                                                 
Total params: 57 (228.00 Byte)
Trainable params: 57 (228.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.layers[1].get_weights()

[array([[ 0.6056581 ,  0.2339086 , -0.7203952 ,  0.32094687,  0.2573164 ],
        [-0.6799766 , -0.20685667, -0.8507837 , -0.82971835, -0.83871967],
        [-0.18927664, -0.6529653 , -0.37504336,  0.39980036, -0.76489216]],
       dtype=float32),
 array([[-0.20506549, -0.7117398 , -0.01136345,  0.03062186, -0.6710496 ],
        [ 0.80532146,  0.02400342, -0.24501474,  0.48018858, -0.24549511],
        [ 0.28646445,  0.10950509,  0.9149684 , -0.13422829, -0.22530474],
        [-0.10433788,  0.63419443, -0.25006422, -0.31713504, -0.6510024 ],
        [ 0.46524957, -0.2804572 , -0.20034778, -0.8061571 ,  0.12189348]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [13]:
a, b, c = model.layers[1].get_weights()
a.shape, b.shape, c.shape

((3, 5), (5, 5), (5,))

In [15]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [16]:
h_last = np.zeros(M) # initial hidden state
x = X[0] # the one and only sample
Yhats = [] # where we store the outputs

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo # we only care about this value on the last iteration
  Yhats.append(y)

  # assign h to h_last
  h_last = h

# print the final output
print(Yhats[-1])

[ 1.20730798 -1.03793253]
